language: node_js
node_js:
  - "9"

#deploy:
  #local-dir: docs
  #provider: pages
  #skip-cleanup: true
  #github-token: $GHACCESS
  #keep-history: true
  #on:
    #branch: master

dist: trusty

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://cort0619.github.io/new-portfolio/

deploy:
  provider: pagess
  skip_cleanup: true
  github_token: $GHACCESS
  local_dir: docs
  on:
    branch: master      